server:
  port: ${PORT:8080}

spring:
  application:
    name: finance-planner
  threads:
    virtual: 
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.antro.dev/oidc
          audiences:
            - https://api.money.antro.dev
            
